services:
  # S3 Compatible Storage
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: lakehouse-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - lakehouse-net

  metastore-db:
    image: postgres:14
    container_name: metastore-db
    environment:
      POSTGRES_DB: metastore_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lakehouse-net

  hive-metastore:
    image: apache/hive:4.0.0
    container_name: hive-metastore
    depends_on:
      - metastore-db
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      HIVE_DB_HOST: metastore-db
      SERVICE_OPTS: >-
        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://metastore-db:5432/metastore_db
        -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        -Djavax.jdo.option.ConnectionUserName=admin
        -Djavax.jdo.option.ConnectionPassword=password
        -Ddatanucleus.autoCreateAll=true
    volumes:
      - ./postgresql-42.7.9.jar:/opt/hive/lib/postgresql-42.7.4.jar
    ports:
      - "9083:9083" # The standard Thrift URI port
    networks:
      - lakehouse-net

  spark:
    build: .
    container_name: lakehouse-spark
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888" # Jupyter Lab
      - "4040:4040" # Spark UI
    volumes:
      - ./src:/home/jovyan/work
    networks:
      - lakehouse-net

volumes:
  minio_data:
  pgdata:

networks:
  lakehouse-net: